// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © JoeTheMaN
// BERT (Be Ever Ready to Trade) Indicator

//@version=5
indicator(title="BERT", overlay=true)

// Inputs
maType = input.string("SMA", "Moving Average", options=["EMA", "SMA"])
maPeriod = input.int(20, "Moving Average Period")


// MOVING AVERAGE
// Plot moving average based on user input
ma = maType == "SMA" ? ta.sma(close, maPeriod) : ta.ema(close, maPeriod)
plot(ma, color=(maType == "SMA") ? color.orange : color.purple, title="MA")

// VWAP
// compute vwap
volumeWAP = ta.vwap(hlc3)

// plot vwap
plot(volumeWAP, color=color.yellow, title="VWAP")

// Plot session open
var float sessionOpen = 0.00
var line l = na

is_new_session = session.isfirstbar
bgcolor(is_new_session ? color.new(color.green, 85) : na)

if (is_new_session)     // New session
    sessionOpen := open  // Reset session high
    l := line.new(bar_index, sessionOpen, bar_index, sessionOpen, color=color.silver, width = 2)    // Get new line id
else
    line.set_x2(l, bar_index)   // Update x2 position of the line (move it to the right)