//@version=5
strategy("Supertrend Strategy", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=15)

atrPeriod = input(10, "ATR Length")
factor = input.float(3.0, "Factor", step = 0.01)
maPeriod = input.int(10, "MA Period (pips)")

// compute the moving average across maPeriod
ma = ta.ema(close, maPeriod)

[_, direction] = ta.supertrend(factor, atrPeriod)

if ta.change(direction) < 0 and ma < close
    strategy.entry("long_entry", strategy.long)
    strategy.close("short_entry")

if ta.change(direction) > 0 and ma > close
    strategy.entry("short_entry", strategy.short)
    strategy.close("long_entry")

// close all entries if ma is crossed, even if direction doesn't change
if (close < ma)
    strategy.close("long_entry")

if (close > ma)
    strategy.close("short_entry")

// plot the moving average as an orange line
plot(ma, color = color.orange, title = "MA")