// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © JoeTheMaN
// MOAI (Mother Of All Indicators) Indicator

//@version=5
indicator(title="MOAI", overlay=true)

// INPUTS
maType = input.string("SMA", "Moving Average", options=["EMA", "SMA"])
maPeriod = input.int(20, "Moving Average Period")

// VARIABLES
var float sessionOpen = 0.00
var line l = na

// MOVING AVERAGE
// Plot moving average based on user input
ma = maType == "SMA" ? ta.sma(close, maPeriod) : ta.ema(close, maPeriod)
plot(ma, color=(maType == "SMA") ? color.orange : color.purple, title="MA")

// VWAP
// compute vwap
volumeWAP = ta.vwap(close, session.isfirstbar)

// plot vwap
plot(volumeWAP, color=color.yellow, title="VWAP")

// Plot session open
isNewSession = session.isfirstbar
bgcolor(isNewSession ? color.new(color.green, 85) : na)

if (isNewSession)     // New session
    sessionOpen := open  // Reset session high
    l := line.new(bar_index, sessionOpen, bar_index, sessionOpen, color=color.silver)    // Get new line id
else
    line.set_x2(l, bar_index)   // Update x2 position of the line (move it to the right)